# services/webfront/nginx.conf
server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # serve files or 404
  location / {
    try_files $uri $uri/ =404;
  }

  # cache static assets a bit
  location ~* \.(png|jpg|jpeg|gif|ico|svg|css|js)$ {
    expires 30d;
    access_log off;
  }
}